[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuantumOptics = "6e0679c1-51ea-5a7c-ac74-d61b76210b0c"
QuantumOpticsBase = "4f57444f-1401-5e15-980d-4471b28d5678"
SteadyStateDiffEq = "9672c7b4-1e72-59bd-8a11-6ac3964bc41f"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Documenter = "1"
Latexify = "0.13, 0.14, 0.15, 0.16"
MacroTools = "0.5"
ModelingToolkit = "9"
OrdinaryDiffEq = "6"
Plots = "1"
QuantumOptics = "1"
QuantumOpticsBase = "0.4.21"
SteadyStateDiffEq = "1"
StochasticDiffEq = "6"
SymbolicUtils = "3.1.2"
Symbolics = "6"
